name: clashy
description: clash ui
publish_to: "none"
version: 1.0.0+1

workspace:
  - packages/common

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  process: ^5.0.6
  yaml: ^3.1.0
  nop_db:
    path: ../packages/nop_db
  nop_db_sqlite:
    path: ../packages/nop_db_sqlite
  useful_tools:
    path: ../packages/useful_tools

  nop: ^0.3.0
  http: ^1.6.0
  dio: ^5.11.1
  file: ^7.0.1
  path: ^1.8.0
  path_provider: ^2.0.7
  win32: ^6.4.0
  ffi: ^2.2.0
  json_annotation: ^4.3.0
  hive_ce:

  clash_core: any
  common: ^0.0.1
  flutter_nop: ^4.0.0
  material_ui: ^1.2.0
  web_socket_channel: ^3.0.3
  crypto: ^3.0.7
  tray_manager: ^0.5.3
  clash_service:
    path: packages/clash_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  nop_gen:
    path: ../packages/nop_gen
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

dependency_overrides:
  flutter_nop:
    path: ../packages/flutter_nop
  nop_db:
    path: ../packages/nop_db
  nop_db_sqlite:
    path: ../packages/nop_db_sqlite
  useful_tools:
    path: ../packages/useful_tools
  nop:
    path: ../packages/nop
  clash_core:
    path: packages/clash_core

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
