// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:clash_core/clash_core.dart')
library;

import 'dart:ffi' as ffi;

/// Starts the core with the configuration found in configDir, mirroring
/// `mihomo -d configDir`. TUN follows whatever the config file declares.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> start(ffi.Pointer<ffi.Char> configDir);

/// Starts the core like start(), but forces `tun.enable` to true. While the core
/// is running this only (re)creates the TUN listener.
///
/// fd is the descriptor of the tun device an Android VpnService already
/// established, and must be transferred to the core: it takes ownership and
/// closes it on shutdown, so do not close the ParcelFileDescriptor as well.
/// Pass 0 (or a negative value) when the core may create the device itself.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int)>()
external ffi.Pointer<ffi.Char> startTun(
  ffi.Pointer<ffi.Char> configDir,
  int fd,
);

/// Stops the core and closes every listener, including TUN.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> stop();

/// Releases a string returned by this library.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void freeString(ffi.Pointer<ffi.Char> s);
