// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final ffi.DynamicLibrary _lib = ffi.DynamicLibrary.open(
  'com.aote.clashy.helper.clash',
);

/// Starts the core with the configuration found in configDir, mirroring
/// `mihomo -d configDir`. TUN follows whatever the config file declares.
final start = _lib
    .lookupFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>),
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)
    >('start');

/// Starts the core like start(), but forces `tun.enable` to true. While the core
/// is running this only (re)creates the TUN listener.
///
/// fd is the descriptor of the tun device an Android VpnService already
/// established, and must be transferred to the core: it takes ownership and
/// closes it on shutdown, so do not close the ParcelFileDescriptor as well.
/// Pass 0 (or a negative value) when the core may create the device itself.
final startTun = _lib
    .lookupFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, ffi.Int),
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>, int)
    >('startTun');

/// Stops the core and closes every listener, including TUN.
final stop = _lib
    .lookupFunction<
      ffi.Pointer<ffi.Char> Function(),
      ffi.Pointer<ffi.Char> Function()
    >('stop');

/// Releases a string returned by this library.
final freeString = _lib
    .lookupFunction<
      ffi.Void Function(ffi.Pointer<ffi.Char>),
      void Function(ffi.Pointer<ffi.Char>)
    >('freeString');
