// C interface of the clashy Go core (github.com/metacubex/mihomo).
//
// Generated by `go build -buildmode=c-shared` from core/main.go; this file only
// declares the hand written entry points so that ffigen can bind them with
// `dart run ffigen --config ffigen.yaml`.
//
// Every function returns NULL on success. On failure it returns a newly
// allocated message that the caller owns and must release with freeString().

#ifndef CLASH_CORE_LIBCLASH_H_
#define CLASH_CORE_LIBCLASH_H_

#ifdef __cplusplus
extern "C" {
#endif

// Starts the core with the configuration found in configDir, mirroring
// `mihomo -d configDir`. TUN follows whatever the config file declares.
char *start(char *configDir);

// Starts the core like start(), but forces `tun.enable` to true. While the core
// is running this only (re)creates the TUN listener.
//
// fd is the descriptor of the tun device an Android VpnService already
// established, and must be transferred to the core: it takes ownership and
// closes it on shutdown, so do not close the ParcelFileDescriptor as well.
// Pass 0 (or a negative value) when the core may create the device itself.
char *startTun(char *configDir, int fd);

// Stops the core and closes every listener, including TUN.
char *stop(void);

// Releases a string returned by this library.
void freeString(char *s);

#ifdef __cplusplus
}
#endif

#endif // CLASH_CORE_LIBCLASH_H_
